# Generated by Django 6.0.5 on 2026-06-18 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0006_alter_review_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompatibilityRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compatibility_type', models.CharField(choices=[('CPU_MB', 'CPU -> Motherboard'), ('RAM_MB', 'RAM -> Motherboard'), ('GPU_PSU', 'GPU -> PSU'), ('GPU_CASE', 'GPU -> CASE')], max_length=20)),
                ('compatible_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compatible_with', to='shop.product')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compatibility_rules', to='shop.product')),
            ],
            options={
                'unique_together': {('product', 'compatible_product', 'compatibility_type')},
            },
        ),
    ]
