# Generated by Django 6.0.5 on 2026-06-18 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compatibility', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compatibilityrule',
            name='compatibility_type',
            field=models.CharField(choices=[('CPU_MB', 'CPU -> Motherboard'), ('RAM_MB', 'RAM -> Motherboard'), ('SSD_MB', 'SSD -> Motherboard'), ('GPU_PSU', 'GPU -> PSU'), ('GPU_CASE', 'GPU -> CASE')], max_length=20),
        ),
    ]
