# Generated by Django 6.0.5 on 2026-06-26 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compatibility', '0002_alter_compatibilityrule_compatibility_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compatibilityrule',
            name='compatibility_type',
            field=models.CharField(choices=[('CPU_MB', 'CPU -> Motherboard'), ('RAM_MB', 'RAM -> Motherboard'), ('SSD_MB', 'SSD -> Motherboard'), ('GPU_PSU', 'GPU -> PSU'), ('GPU_CASE', 'GPU -> Case'), ('MB_CASE', 'Motherboard -> Case')], max_length=20),
        ),
    ]
