# Generated by Django 6.0.5 on 2026-06-16 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='form_factor',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='gpu_length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='power_required',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='storage_type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
