# Generated by Django 6.0.5 on 2026-06-19 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_review_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='max_gpu_length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='psu_wattage',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
