# Generated by Django 6.0.5 on 2026-06-23 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_product_base_clock_ghz_product_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='nmve_support',
            field=models.BooleanField(default=False),
        ),
    ]
