# Generated by Django 6.0.5 on 2026-06-23 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_product_nmve_support'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='nmve_support',
            new_name='nvme_support',
        ),
    ]
