# Generated by Django 6.0.5 on 2026-06-19 16:21

import uuid
from django.db import migrations, models

def generate_tokens(apps, schema_editor):

    Order = apps.get_model('orders', 'Order')

    for order in Order.objects.all():

        order.token = uuid.uuid4()
        order.save(update_fields=['token'])


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='token',
            field=models.UUIDField(null=True, editable=False),
        ),

        migrations.RunPython(generate_tokens),

        migrations.AlterField(
            model_name='order',
            name='token',
            field=models.UUIDField(
                default = uuid.uuid4,
                editable=False,
                unique=True
            ),
        ),
    ]
