# Generated by Django 6.0.5 on 2026-06-27 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='paid',
        ),
    ]
